image: "rust:latest"

.linux_build:
  script:
    - apt-get update
    - >
      apt-get install -y gcc pkg-config openssl libasound2-dev cmake
      build-essential libfreetype6-dev libexpat1-dev
      libxcb-composite0-dev libssl-dev
    - cargo build --release
    - mkdir -p build/pizzatopia-amethyst
    - mv target/release/pizzatopia-amethyst build/pizzatopia-amethyst
    - cp -R assets build/pizzatopia-amethyst
    - cp -R config build/pizzatopia-amethyst
    - cd build/
    - tar -czf pizzatopia-amethyst-linux-x86_64.tgz pizzatopia-amethyst
  artifacts:
    paths:
    - build/pizzatopia-amethyst-linux-x86_64.tgz
    expire_in: 1 week
  only:
    - tags

test:
  script:
    - ls .

.mac_build:
  script:
      # Install Cross-compiler toolchain
      - apt-get update
      - apt-get install -y clang cmake cpio make libssl-dev lzma-dev libxml2-dev
      - rustup target add x86_64-apple-darwin
      - mkdir -p /build
      - cd /build
      - git clone --depth 1 https://github.com/tpoechtrager/osxcross.git
      - cd /build/osxcross/tarballs
      - wget https://s3.dockerproject.org/darwin/v2/MacOSX10.11.sdk.tar.xz
      - cd /build/osxcross
      - UNATTENDED=yes OSX_VERSION_MIN=10.7 ./build.sh
      - export PATH="$PATH:/build/osxcross/target/bin"
      - ln -s /build/osxcross/target/SDK/MacOSX10.11.sdk/System/ /System
      # Configure build to use Mac linker and libraries
      - mkdir -p /pizzatopia/.cargo
      - |
        echo '[target.x86_64-apple-darwin]
        linker = "x86_64-apple-darwin15-clang"' >> /pizzatopia/.cargo/config
      - cd /pizzatopia
      - echo "[replace]" >> Cargo.toml # Patch coreaudio-sys so that it can be cross-compiled on Linux
      - >
        echo '"coreaudio-sys:0.2.2" =
        { git = "https://github.com/RustAudio/coreaudio-sys.git",
        rev = "13a32d7" }' >> Cargo.toml
      - cargo update
      - export COREAUDIO_FRAMEWORKS_PATH='/System/Library/Frameworks'
      - >
        export COREAUDIO_CFLAGS='-I/System/Library/Frameworks/Kernel.framework/Headers
        -I/build/osxcross/target/SDK/MacOSX10.11.sdk/usr/include'
      - export CC=x86_64-apple-darwin15-clang
      - cargo build --target x86_64-apple-darwin --release
      - mkdir -p build/pizzatopia-amethyst
      - mv target/x86_64-apple-darwin/release/pizzatopia-amethyst build/pizzatopia-amethyst
      - cp -R assets build/pizzatopia-amethyst
      - cp -R config build/pizzatopia-amethyst
      - cd build/
      - tar -czf pizzatopia-amethyst-mac-x86_64.tgz pizzatopia-amethyst
  artifacts:
    paths:
      - build/pizzatopia-amethyst-mac-x86_64.tgz
    expire_in: 1 week
  only:
    - tags


.windows_build:
  script:
    - apt-get update
    - >
      apt-get install -y gcc gcc-mingw-w64 pkg-config openssl libasound2-dev
      cmake build-essential libfreetype6-dev libexpat1-dev
      libxcb-composite0-dev libssl-dev zip
    - rustup target install x86_64-pc-windows-gnu
    - mkdir -p .cargo
    - |
      echo '[target.x86_64-pc-windows-gnu]
      linker = "x86_64-w64-mingw32-gcc"' >> .cargo/config
    - cargo build --target x86_64-pc-windows-gnu --release
    - mkdir -p build/pizzatopia-amethyst
    - mv target/x86_64-pc-windows-gnu/release/pizzatopia-amethyst.exe build/pizzatopia-amethyst
    - cp -R assets build/pizzatopia-amethyst
    - cp -R config build/pizzatopia-amethyst
    - cd build/
    - zip -r pizzatopia-amethyst-windows-x86_64.zip pizzatopia-amethyst
  artifacts:
    paths:
      - build/pizzatopia-amethyst-windows-x86_64.zip
    expire_in: 1 week
  only:
    - tags
