[package]
name = "pizzatopia"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.15"
#amethyst = {  git = "https://github.com/amethyst/amethyst.git", branch = "master", features = ["vulkan", "no-slow-safety-checks"]}
log = "0.4.8"
serde = { version = "1.0", features = ["derive"] }
derivative = "1.0.3"
ron = "*"

[features]
default = ["vulkan"]
vulkan = ["amethyst/vulkan"]
metal = ["amethyst/metal"]
