[package]
name = "pizzatopia-amethyst"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
#amethyst = "0.13.2"
amethyst = {  git = "https://github.com/amethyst/amethyst.git", branch = "0.13.2", features = ["vulkan", "no-slow-safety-checks"]}
log = "0.4.8"

[features]
default = ["vulkan"]
vulkan = ["amethyst/vulkan"]
metal = ["amethyst/metal"]
