[package]
name = "pizzatopia-amethyst"
# major-minor-patch
version = "0.0.1"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.13.2"
log = "0.4.8"

[features]
default = ["vulkan"]
vulkan = ["amethyst/vulkan"]
metal = ["amethyst/metal"]
