[package]
name = "pizzatopia-amethyst"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.13.2"
smart-default = "0.5.2"

[features]
default = ["vulkan"]
vulkan = ["amethyst/vulkan"]
